### PR TITLE
优化fix #39 #40 #41

### LINKED ISSUE #39: [Bug]: 生存模式点击领地里的龙蛋，龙蛋会被打飞
### Describe the bug | 描述错误

不能拦截龙蛋交互

### To Reproduce | 重现步骤

请看VCR
https://www.123912.com/s/OIsvjv-x3n5H

### Expected behavior | 预期行为

修复

### Screenshots | 截图

_No response_

### Platform | 平台

win10

### BDS Version | BDS版本

1.21.60

### LeviLamina Version | LeviLamina版本

1.1.1

### Version | 版本

7.1

### Additional context | 其他上下文

_No response_

### PR DESCRIPTION
**Pull request by yangyangzhong82**
## Checklist before merging

Thank you for your contribution to the repository. 
Before submitting this PR, please make sure:

- [ ] Your code builds clean without any errors or warnings
- [ ] Your code follows [LeviLamina C++ Style Guide](https://github.com/LiteLDev/LeviLamina/wiki/CPP-Style-Guide)
- [ ] You have tested all functions
- [ ] You have not used code without license
- [ ] You have added statement for third-party code

### CODE REVIEW

File: include/pland/DataConverter.h [hunk 1]
```diff
@@ -75,6 +75,8 @@ class iLandConverter : public DataConverter {
             } settings;
 
             struct {
+                bool place_minecart;
```
Comment (engsr6982) [inline include/pland/DataConverter.h]: 感谢PR, 请问 iland 有这个权限吗？

File: include/pland/LandData.h [hunk 2]
```diff
@@ -51,6 +51,8 @@ struct LandPermTable {
     bool useBlastFurnace{false};     // 使用高炉
     bool useBrewingStand{false};     // 使用酿造台
     bool useCampfire{false};         // 使用营火
+    bool placeBoat{false};           // 放置船
```
Comment (engsr6982) [inline include/pland/LandData.h:52]: 这里修改了 LandData 的成员，LandData::version 需要递增
